name: cognitive_journal
description: A cognitive journal app with purple theme

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.66.2
  pdf: ^3.10.4
  printing: ^5.11.2
  path_provider: ^2.1.1 
  permission_handler: ^11.0.1
  open_file: ^3.3.1
  shared_preferences: ^2.2.2
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true